### ISSUE TITLE
Adjust primary text size

### ISSUE THREAD

**Issue by ddamato** [damato-design/system#8]
Primary text should adjust depending on a width.

- The minimum size should be _always_ at least slightly larger[^1] than the secondary size at the current density.
- There should be a purpose[^2] behind the maximum size.
- The adjustment cannot be done by container. This would cause similar levels to appear inconsistent. If an adjustment is to happen, it should be related to the device width (`vw`).
- Using viewport units requires math to include `rem` to support user font preferences.[^3]

I _think_ the approach that avoids reflowing text [found here](https://css-tricks.com/linearly-scale-font-size-with-css-clamp-based-on-the-viewport/) is what we want specifically for primary text. Our change would be that at each density shift, the minimum size would update to a new number based on the typescale calculation.

To start, most likely need to lean into the concepts of a minimum and a scale factor to result in a logical progression of sizes. This probably means there are tokens like the following:

- `text.primary.minSize`
- `text.primary.scaleFactor`
- `text.secondary.minSize`
- `text.secondary.scaleFactor`
- `text.auxiliary.minSize`
- `text.auxiliary.scaleFactor`

The separations will be important, especially in the case where customized headings are different from body copy.

Without considering the primary text adjustments, the final sizes will only need to consider the `depth` (based on number of predefined density shifts). `depth = 0` is the lowest, resulting in applying the given `minSize` for that purpose.

```css
.text[secondary] {
  font-size: calc(text.secondary.minSize * pow(text.secondary.scaleFactor, depth));
}
```

For avoiding text reflow, the ratio between font sizes and viewport widths must stay the same. In this example, we go from 1rem at 320px to 3rem at 960px.

```
320 / 1 = 320
960 / 3 = 320
```

In the `clampBuilder` function from the post, you'd put in 4 values. However we can compute some of these since they need to stay at the same ratio. Some notes on these numbers:

#### Minimum viewport size (`320px` or `20rem`)
 I'll agree that `320px` is an acceptable minimum viewport size.

#### Minimum font-size (`calc(min * pow(scale, depth))`)
This is a calculation based on tokens shown above. The result of `depth: 0` is equal to the given `min` (`= min * 1`).

#### Maximum viewport size (`60rch` or `30rem`)
I'm not sure if this is viewport size as much as it is preferred reading length for primary text. I cannot find research on what this length is, only the length for body text. However, we _could_ use root units units to use the same length. There are many opinions in this area but a number that seems to appear in all of them is 60 characters. We can use `rch` units to represent one character in the "body" font to get the final value.

Since we have 3 of the 4 numbers, and the ratio is meant to be maintained, we should be able to get the fourth number (max font size) from this.

```
fontmax = (viewmax * fontmin) / viewmin
```

[Prototype here](https://codepen.io/fauxserious/pen/yLmzVRK/bf661a7b4e8ad446974d4d731e5fee6d). Since the whole calculation works in ratios, I'd decided to remove the units from the initial numbers and use a bit of Hungarian notation to indicate where something is expecting a number as `rem`, so `text.primary.minSize` is now `text.primary.minrem`.

The result is that the lockup and wrapping of text is maintained between `320px` and `60rch` in a linear progression for the primary text depending on the viewport width. An artifact of maintaining the ratio is that the final `rem` in the calculation being added to the `vw` units ends at `0rem`. I've checked in the CodePen to ensure that zoom still works as is the concern described in [this post](https://www.smashingmagazine.com/2023/11/addressing-accessibility-concerns-fluid-type/).

[^1]: What does "slightly larger" mean exactly?
[^2]: Why do we resize "primary" text (headings) at all?
[^3]: Do we internalize the calculation or provide guidance and tools to visualize the results?

**Comment by AliAbushariaa** [comment]
Can I work on this issue ?

**Comment by ddamato** [comment]
> Can I work on this issue ?

Thanks for your interest, what experience do you have in this area?

**Comment by ddamato** [comment]
Done. Just need to connect it with the theming system.
